import { styled, theme } from '../stitches.config';

export const Row = styled('div', {
  $space$gutterX: '1.5rem',
  $space$gutterY: '0',
  display: 'flex',
  flexWrap: 'wrap',
  marginTop: `calc(${theme.space.gutterY} * -1)`,
  marginRight: `calc(${theme.space.gutterX} * -.5)`,
  marginLeft: `calc(${theme.space.gutterX} * -.5)`,

  '& > *': {
    flexShrink: 0,
    width: '100%',
    maxWidth: '100%',
    paddingRight: `calc(${theme.space.gutterX} * .5)`,
    paddingLeft: `calc(${theme.space.gutterX} * .5)`,
    marginTop: theme.space.gutterY,
  },
  variants: {
    rowCols: {
      auto: { '& > *': { flex: '0 0 auto', width: 'auto' } },
      1: { '& > *': { flex: '0 0 auto', width: '100%' } },
      2: { '& > *': { flex: '0 0 auto', width: '50%' } },
      3: { '& > *': { flex: '0 0 auto', width: '33.3333333333%' } },
      4: { '& > *': { flex: '0 0 auto', width: '25%' } },
      5: { '& > *': { flex: '0 0 auto', width: '20%' } },
      6: { '& > *': { flex: '0 0 auto', width: '16.6666666667%' } },
    },
    g: {
      0: { $space$gutterX: '0', $space$gutterY: '0' },
      1: { $space$gutterX: '.25rem', $space$gutterY: '.25rem' },
      2: { $space$gutterX: '.5rem', $space$gutterY: '.5rem' },
      3: { $space$gutterX: '1rem', $space$gutterY: '1rem' },
      4: { $space$gutterX: '1.5rem', $space$gutterY: '1.5rem' },
      5: { $space$gutterX: '3rem', $space$gutterY: '3rem' },
    },
    gX: {
      0: { $space$gutterX: '0' },
      1: { $space$gutterX: '.25rem' },
      2: { $space$gutterX: '.5rem' },
      3: { $space$gutterX: '1rem' },
      4: { $space$gutterX: '1.5rem' },
      5: { $space$gutterX: '3rem' },
    },
    gY: {
      0: { $space$gutterY: '0' },
      1: { $space$gutterY: '.25rem' },
      2: { $space$gutterY: '.5rem' },
      3: { $space$gutterY: '1rem' },
      4: { $space$gutterY: '1.5rem' },
      5: { $space$gutterY: '3rem' },
    },
    align: {
      start: { alignItems: 'flex-start' },
      center: { alignItems: 'center' },
      end: { alignItems: 'flex-end' },
      stretch: { alignItems: 'stretch' },
      baseline: { alignItems: 'baseline' },
    },
    justify: {
      start: { justifyContent: 'flex-start' },
      center: { justifyContent: 'center' },
      end: { justifyContent: 'flex-end' },
      between: { justifyContent: 'space-between' },
      around: { justifyContent: 'space-around' },
      evenly: { justifyContent: 'space-evenly' },
    },
  },
});

export const Col = styled('div', {
  variants: {
    col: {
      true: { flex: '1 0 0%' },
      auto: { flex: '0 0 auto', width: 'auto' },
      1: { flex: '0 0 auto', width: '8.33333333%' },
      2: { flex: '0 0 auto', width: '16.66666667%' },
      3: { flex: '0 0 auto', width: '25%' },
      4: { flex: '0 0 auto', width: '33.33333333%' },
      5: { flex: '0 0 auto', width: '41.66666667%' },
      6: { flex: '0 0 auto', width: '50%' },
      7: { flex: '0 0 auto', width: '58.33333333%' },
      8: { flex: '0 0 auto', width: '66.66666667%' },
      9: { flex: '0 0 auto', width: '75%' },
      10: { flex: '0 0 auto', width: '83.33333333%' },
      11: { flex: '0 0 auto', width: '91.66666667%' },
      12: { flex: '0 0 auto', width: '100%' },
    },
    offset: {
      1: { marginLeft: '8.33333333%' },
      2: { marginLeft: '16.66666667%' },
      3: { marginLeft: '25%' },
      4: { marginLeft: '33.33333333%' },
      5: { marginLeft: '41.66666667%' },
      6: { marginLeft: '50%' },
      7: { marginLeft: '58.33333333%' },
      8: { marginLeft: '66.66666667%' },
      9: { marginLeft: '75%' },
      10: { marginLeft: '83.33333333%' },
      11: { marginLeft: '91.66666667%' },
    },
    order: {
      first: { order: -1 },
      0: { order: 0 },
      1: { order: 1 },
      2: { order: 2 },
      3: { order: 3 },
      4: { order: 4 },
      5: { order: 5 },
      last: { order: 6 },
    },
  },
});
